# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Headplane installation tasks
  tags:
    - setup-all
    - setup-headplane
    - install-all
    - install-headplane
  block:
    - name: Validate Headplane configuration
      when: headplane_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Headplane
      when: headplane_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Headplane uninstallation tasks
  tags:
    - setup-all
    - setup-headplane
  block:
    - name: Uninstall Headplane
      when: not headplane_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
